### ISSUE TITLE
Pypi timeout produces a broken but "successful" update

### ISSUE THREAD

**Issue by anadahz** [OpenObservatory/lepidopter-update#7]
`/var/log/ooni/lepidopter-update.log` output:

```
INFO:root:Checking for update
INFO:root:Updating 0->1
INFO:root:Running install script
ERROR:root:Command '['pip', 'install', '--upgrade', 'https://github.com/TheTorProject/ooni-probe/releases/download/v2.0.0-rc.2/ooniprobe-2.0.0rc2.tar.gz']' returned non-zero exit status 2
Traceback (most recent call last):
  File "/opt/ooni/lepidopter-update/versions/update-1.py", line 262, in run
    _perform_update()
  File "/opt/ooni/lepidopter-update/versions/update-1.py", line 250, in _perform_update
    check_call(["pip", "install", "--upgrade", OONIPROBE_PIP_URL])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['pip', 'install', '--upgrade', 'https://github.com/TheTorProject/ooni-probe/releases/download/v2.0.0-rc.2/ooniprobe-2.0.0rc2.tar.gz']' returned non-zero exit status 2
INFO:root:Updated to version 1
```

`/root/.pip/pip.log` excerpt:

```
  Using version 1.8.2 (newest of versions: 1.8.2, 1.7.0, 1.6.0, 1.5.2, 1.5.1, 1.5.0, 1.4.2, 1.4.1)
  Downloading from URL https://pypi.python.org/packages/b8/21/9d6f08d2d36a0a8c84623646b4ed5a07023d868823361a086b021fb21172/cffi-1.8.2.tar.gz#md5=538f307b6c5169bba41fbfda2b070762 (from https://pypi.python.org/simple/cffi/)
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1198, in prepare_files
    do_download,
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1376, in unpack_url
    self.session,
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 572, in unpack_http_url
    download_hash = _download_url(resp, link, temp_location)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 433, in _download_url
    for chunk in resp_read(4096):
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 421, in resp_read
    chunk_size, decode_content=False):
  File "/usr/lib/python2.7/dist-packages/urllib3/response.py", line 256, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/lib/python2.7/dist-packages/urllib3/response.py", line 210, in read
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
ReadTimeoutError: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out.
```

Restarting lepidopter-update service does nothing since the `/etc/lepidopter-update/version` is `1`.

```
INFO:root:Checking for update
INFO:root:Already up to date
```

By default after upgrade ooniprobe service is not running as expected:
`# systemctl status ooniprobe -l`

```
� ooniprobe.service - ooniprobe.service, network interference detection tool
   Loaded: loaded (/etc/systemd/system/ooniprobe.service; disabled)
   Active: inactive (dead)
```

Restarting ooniprobe service does start the ooniprobe-agent.

**Comment by hellais** [comment]
Yes, this is a problem with the update-1.py script. It's swallowing the exception and not re-rasing it.

Will push a fix.
