### ISSUE TITLE
update-2.py endless loop

### ISSUE THREAD

**Issue by anadahz** [OpenObservatory/lepidopter-update#9]
`/etc/lepidopter-update/version` `1`

It seems that the update-2.py is causing an endless loop to the updater.

```
2016-09-20 12:53:54,411 - INFO - Checking for update
2016-09-20 12:53:58,477 - INFO - Updating 1->2
2016-09-20 12:54:01,909 - INFO - Checking for update
2016-09-20 12:54:06,501 - INFO - Updating 1->2
2016-09-20 12:54:12,418 - INFO - Checking for update
2016-09-20 12:54:14,129 - INFO - Updating 1->2
2016-09-20 12:54:17,671 - INFO - Checking for update
[...]
```

`# systemctl status lepidopter-update -l`

```
� lepidopter-update.service - lepidopter-update service
   Loaded: loaded (/etc/systemd/system/lepidopter-update.service; enabled)
   Active: active (running) since Tue 2016-09-20 12:55:30 UTC; 6s ago
 Main PID: 6567 (python2)
   CGroup: /system.slice/lepidopter-update.service
           �6567 python2 /opt/ooni/lepidopter-update/updater.py --log-file /var/log/ooni/lepidopter-update.log update --watch
           �6576 curl -q -L https://github.com/OpenObservatory/lepidopter-update/releases/download/2/update.py.asc

Sep 20 12:55:31 lepidopter updater.py[6567]: Dload  Upload   Total   Spent    Left  Speed
Sep 20 12:55:34 lepidopter updater.py[6567]: [392B blob data]
Sep 20 12:55:35 lepidopter updater.py[6567]: [155B blob data]
Sep 20 12:55:35 lepidopter updater.py[6567]: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Sep 20 12:55:35 lepidopter updater.py[6567]: Dload  Upload   Total   Spent    Left  Speed
Sep 20 12:55:35 lepidopter updater.py[6567]: [155B blob data]
Sep 20 12:55:36 lepidopter updater.py[6567]: [155B blob data]
Sep 20 12:55:36 lepidopter updater.py[6567]: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Sep 20 12:55:36 lepidopter updater.py[6567]: Dload  Upload   Total   Spent    Left  Speed
Sep 20 12:55:37 lepidopter updater.py[6567]: [234B blob data]
```

**Comment by hellais** [comment]
Is there a way to check if the updater is being restarted by systemd and if so the reason why it has failed and is being restarted?

I suspect that the loop is actually not an endless loop, but rather that the updater is failing with an un-handled exception and is therefore exiting and systemd is then restarting it.

**Comment by anadahz** [comment]
According to the current status:
`Active: active (running) since Tue 2016-09-20 13:23:40 UTC; 3h 40min ago`,
it seems that has restarted at least once specifically at 13:23:40 UTC.
Comparing the times to `/var/log/ooni/lepidopter-update.log` makes sense:

```
2016-09-20 13:23:41,166 - INFO - Checking for update
2016-09-20 13:23:42,407 - INFO - Updating 1->2
2016-09-20 13:27:19,394 - ERROR - Failed to download update file
2016-09-20 13:27:19,395 - ERROR - Failed to update to version 2
```

### journalctl excerpt

```
Sep 20 12:54:58 lepidopter systemd[1]: Starting lepidopter-update service...
Sep 20 12:54:58 lepidopter systemd[1]: Started lepidopter-update service.
Sep 20 12:54:58 lepidopter updater.py[6503]: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Sep 20 12:54:58 lepidopter updater.py[6503]: Dload  Upload   Total   Spent    Left  Speed
Sep 20 12:54:59 lepidopter updater.py[6503]: [234B blob data]
Sep 20 12:55:00 lepidopter updater.py[6503]: [155B blob data]
Sep 20 12:55:00 lepidopter updater.py[6503]: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Sep 20 12:55:00 lepidopter updater.py[6503]: Dload  Upload   Total   Spent    Left  Speed
Sep 20 12:55:00 lepidopter updater.py[6503]: [155B blob data]
Sep 20 12:55:01 lepidopter updater.py[6503]: [155B blob data]
Sep 20 12:55:01 lepidopter updater.py[6503]: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Sep 20 12:55:01 lepidopter updater.py[6503]: Dload  Upload   Total   Spent    Left  Speed
Sep 20 12:55:02 lepidopter updater.py[6503]: [234B blob data]
Sep 20 12:55:03 lepidopter updater.py[6503]: [155B blob data]
Sep 20 12:55:03 lepidopter updater.py[6503]: Traceback (most recent call last):
Sep 20 12:55:03 lepidopter updater.py[6503]: File "/opt/ooni/lepidopter-update/updater.py", line 387, in <module>
Sep 20 12:55:03 lepidopter updater.py[6503]: main()
Sep 20 12:55:03 lepidopter updater.py[6503]: File "/opt/ooni/lepidopter-update/updater.py", line 383, in main
Sep 20 12:55:03 lepidopter updater.py[6503]: args.func(args)
Sep 20 12:55:03 lepidopter updater.py[6503]: File "/opt/ooni/lepidopter-update/updater.py", line 304, in update
Sep 20 12:55:03 lepidopter updater.py[6503]: check_for_update(skip_verification=args.skip_verification)
Sep 20 12:55:03 lepidopter updater.py[6503]: File "/opt/ooni/lepidopter-update/updater.py", line 266, in check_for_update
Sep 20 12:55:03 lepidopter updater.py[6503]: update_to_version(current_version, latest_version, skip_verification)
Sep 20 12:55:03 lepidopter updater.py[6503]: File "/opt/ooni/lepidopter-update/updater.py", line 250, in update_to_version
Sep 20 12:55:03 lepidopter updater.py[6503]: perform_update(version, skip_verification)
Sep 20 12:55:03 lepidopter updater.py[6503]: File "/opt/ooni/lepidopter-update/updater.py", line 206, in perform_update
Sep 20 12:55:03 lepidopter updater.py[6503]: with open(updater_path, "w+") as out_file:
Sep 20 12:55:03 lepidopter updater.py[6503]: IOError: [Errno 2] No such file or directory: '/opt/ooni/lepidopter-update/versions/update-2.py'
Sep 20 12:55:03 lepidopter systemd[1]: lepidopter-update.service: main process exited, code=exited, status=1/FAILURE
Sep 20 12:55:03 lepidopter systemd[1]: Unit lepidopter-update.service entered failed state.
Sep 20 12:55:03 lepidopter systemd[1]: lepidopter-update.service holdoff time over, scheduling restart.
Sep 20 12:55:03 lepidopter systemd[1]: Stopping lepidopter-update service...
```

**Comment by anadahz** [comment]
`# curl -q -L https://github.com/OpenObservatory/lepidopter-update/releases/download/2/update.py`

```
"""
This is the auto update script for going from version 1 to version 2.
"""

import logging

from subprocess import check_call

__version__ = "2"

OONIPROBE_PIP_URL = "https://github.com/TheTorProject/ooni-probe/releases/download/v2.0.0-rc.3/ooniprobe-2.0.0rc3.tar.gz"

def _perform_update():
    check_call(["pip", "install", "--upgrade", OONIPROBE_PIP_URL])

def run():
    check_call(["systemctl", "stop", "ooniprobe"])
    try:
        _perform_update()
    except Exception as exc:
        logging.exception(exc)
        raise
    finally:
        check_call(["systemctl", "start", "ooniprobe"])

if __name__ == "__main__":
    run()
```

**Comment by hellais** [comment]
Can you give me the output of:

```
tree /opt/ooni/lepidopter-update
```

From the output I see there, it looks like you don't have the `/opt/ooni/lepidopter-update/versions` directory.

**Comment by hellais** [comment]
Ok, so it seems like the this an issue with the latest lepidopter image. It doesn't have the `/opt/ooni/lepidopter-update/versions/` directory: https://github.com/TheTorProject/lepidopter/tree/master/lepidopter-fh/opt/ooni/lepidopter-update.

**Comment by anadahz** [comment]
Yes you are right!
@hellais  is it OK adding a `.gitkeep` file in `/opt/ooni/lepidopter-update/versions/` or lepidopter-update doesn't like non update files?

**Comment by hellais** [comment]
I would recommend you commit to that directory the update-1.py and update-1.py.asc files since those are actually what would be on the filesystem of a version 1 image.
